package types

type PipeSeparatedFlagsSimpleQueryStringFlag any

type PipeSeparatedFlagsSimpleQueryStringFlagVariant interface {
	PipeSeparatedFlagsSimpleQueryStringFlagCaster() *PipeSeparatedFlagsSimpleQueryStringFlag
}
